### ISSUE TITLE
install this plugin

### ISSUE THREAD

**Issue by AleksKavil** [Dytser/MHR-Mesh-Panel#1]
Hi, I can't install this plugin, I'm using blender 2.93
![s](https://user-images.githubusercontent.com/120709542/213908728-e2c664fe-27f4-4010-bd82-1db08af08c0f.png)

**Comment by Dytser** [comment]
Try unpacking it first and install the .py files by themselves, i always installed the .py files and dont even have them zipped up atm on my own PC.

Although i cant verify the plugin effect for older versions as i personally use 3.3.1 atm

If installing the Py files doesnt work can you send the actual log output of what it says so i can try to narrow down wahts actually causing it

**Comment by Dytser** [comment]
Closing issue due to no follow up and very likely a user error.
